# Generated by Django 4.0.1 on 2022-01-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterequipment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='characterequipment',
            constraint=models.UniqueConstraint(fields=('character', 'slot'), name='unique_character_slot'),
        ),
    ]
