# Generated by Django 4.0.1 on 2022-01-17 07:00

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_characterequipment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_character_name'),
        ),
    ]
