# Generated by Django 4.0.2 on 2022-02-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_created_at_character_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='current_hp',
        ),
    ]
