# Generated by Django 4.0.2 on 2022-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_character_current_hp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='characterinventory',
            constraint=models.UniqueConstraint(fields=('character', 'item'), name='unique_character_item'),
        ),
    ]
