# Generated by Django 4.0.1 on 2022-01-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('level_requirement', models.IntegerField()),
                ('min_damage', models.IntegerField()),
                ('max_damage', models.IntegerField()),
                ('min_armour', models.IntegerField()),
                ('max_armour', models.IntegerField()),
                ('value', models.IntegerField()),
                ('type', models.CharField(choices=[('weapon', 'Weapon'), ('armour', 'Armour'), ('helmet', 'Helmet'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('ring', 'Ring')], default='weapon', max_length=20, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('level_requirement', models.IntegerField()),
                ('min_damage', models.IntegerField()),
                ('max_damage', models.IntegerField()),
                ('min_armour', models.IntegerField()),
                ('max_armour', models.IntegerField()),
                ('value', models.IntegerField()),
                ('type', models.CharField(choices=[('weapon', 'Weapon'), ('armour', 'Armour'), ('helmet', 'Helmet'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('ring', 'Ring')], default='weapon', max_length=20, verbose_name='type')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
