# Generated by Django 4.0.2 on 2022-02-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_created_at_item_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='level_requirement',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max_armour',
        ),
        migrations.RemoveField(
            model_name='item',
            name='max_damage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_armour',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_damage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='value',
        ),
    ]
