# Generated by Django 4.0.2 on 2022-02-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_level_requirement_remove_item_max_armour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='is_purchasable',
            field=models.BooleanField(default=False, verbose_name='Is purchasable'),
        ),
    ]
