# Generated by Django 4.0.2 on 2022-02-26 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_remove_characterinventory_character_and_more'),
        ('items', '0005_itemtemplate_is_purchasable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='characters.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='container_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('equipment', 'Equipment')], default='inventory', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armour', 'Armour'), ('helmet', 'Helmet'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('ring', 'Ring')], default='weapon', max_length=20),
        ),
    ]
