# Generated by Django 4.0.2 on 2022-02-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_character_item_container_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='container_type',
            new_name='container',
        ),
    ]
