# Generated by Django 4.0.2 on 2022-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_container_type_item_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bonus_max_armour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_max_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_min_armour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_min_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='has_bonuses',
            field=models.BooleanField(default=False),
        ),
    ]
